# Generated by Django 3.0.7 on 2020-06-11 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_cargo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_pessoa', models.CharField(max_length=200)),
                ('dt_admissao', models.DateTimeField(auto_now_add=True)),
                ('id_cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prova.Cargos')),
            ],
        ),
    ]
