# Generated by Django 3.0.7 on 2020-06-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prova', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoas',
            name='dt_admissao',
            field=models.DateTimeField(),
        ),
    ]
